// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB172RXy9TLeM2Cmo-P4amvgRhX17iqz0k',
    appId: '1:939364507023:web:ade5079334ab7746bafffa',
    messagingSenderId: '939364507023',
    projectId: 'furever-home-6ed6d',
    authDomain: 'furever-home-6ed6d.firebaseapp.com',
    storageBucket: 'furever-home-6ed6d.firebasestorage.app',
    measurementId: 'G-YZNS40M2DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC63_X0ZWaz-MSLR-JEYFEAEa22-0v8pd8',
    appId: '1:939364507023:android:1844c9406ad3a32cbafffa',
    messagingSenderId: '939364507023',
    projectId: 'furever-home-6ed6d',
    storageBucket: 'furever-home-6ed6d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB172RXy9TLeM2Cmo-P4amvgRhX17iqz0k',
    appId: '1:939364507023:web:f5bfc1b1fe9dffaabafffa',
    messagingSenderId: '939364507023',
    projectId: 'furever-home-6ed6d',
    authDomain: 'furever-home-6ed6d.firebaseapp.com',
    storageBucket: 'furever-home-6ed6d.firebasestorage.app',
    measurementId: 'G-DY600WD6KP',
  );

}